# your domain
domain: late-term-0b91.734519508.workers.dev

# database url
database_url: ""

# cloudflare api
cf_email: ""
cf_key: ""

# source definition file
source-files:
  # use local file
  - ./config/source.yaml
  # use web file
  - https://late-term-0b91.734519508.workers.dev/source.yaml
