# your domain
domain: dafeige288.herokuapp.com

# database url
database_url: ""

# cloudflare api
cf_email: ""
cf_key: ""

# source definition file
source-files:
  # use local file
  
  # use web file
  - https://raw.githubusercontent.com/jfplyl999/v2ray/master/source.yaml
